Solve deploy in preprod new package validata table
etalab/validata.etalab.studio pull request #16
Opened 2023-10-26 13:23 UTC by amelie-rondot

Cette PR a pour but :
- d'annuler les modifications apportées par le merge de cette [PR13](https://github.com/etalab/validata.etalab.studio/pull/13) (par un `git revert`) qui n'ont pas lieu d'être
- de modifier dans le Dockerfile la commande `gunicorn` pour considérer le bon chemin d'accès au module de l'application du sous-package de `validata_ui`, corrigeant ainsi le problème de déploiement en preprod observé suite au merge de cette [PR12](https://github.com/etalab/validata.etalab.studio/pull/12)

Procédure de test réalisé sur cette branche de travail en local :
- Rajout du fichier .env en prenant soin de déclarer les variables d'environnement `FLASK_SECRET_KEY`, `ENV_NAME` et `PORT_NUMBER`
- Lancement du docker-compose : `docker-compose up --build -d`

Résultat observé :
- une image Docker se crée correctement en installant le nouveau package `validata-table`, version v0.10.1 comme souhaité dans le fichier `requirements.txt`
- un nouveau conteneur se crée correctement en lançant l'interface utilisateur accessible  
  à l'adresse localhost:<`PORT_NUMBER`>
  Le numéro de version indiqué en bas à gauche de la page (0.10.1) permet de prouver que l'interface utilisateur est bien basée sur le nouveau package `validata-table`, version v0.10.1.

NB : lors du déploiement en preprod il faudra modifier le fichier .env afin de rajouter la variable d'environnement FLASK_SECRET_KEY, préalablement au lancement du docker-compose

2023-10-27 10:07 UTC, geoffreyaldebert requested changes
ok super c'est déjà beaucoup plus concis merci @amelie-rondot ! est-ce qu'on en profiterait pas pour : 
- merger nos deux repos validata.etalab.studio et api.validata.etalab.studio en un seul, et je proposerai que ce soit celui-là sur cette PR
- du coup ajouter un dockerfile  et un docker-compose spécial api sur ce repo

ça me semblerait plus simple à gérer, qu'en penses-tu ?

2023-10-27 10:50 UTC, amelie-rondot commented
Oui, ça me va.
Je fais modifie la PR en conséquence d'ici cette fin d'après-midi.

2023-10-27 15:31 UTC, amelie-rondot commented
J'ai rajouté les fichiers `Dockerfile.api.yml`, `docker-compose.api.yml` et `.env.example`.

On pourra désormais déployer directement l'API et l'interface utilisateur à partir du même répertoire `validata.etalab.studio/`  en prod (ou `preprod.validata.etalab.studio/`en preprod) en lançant :
`docker-compose -f docker-compose.yml -f docker-compose.api.yml --build -d`

Ca créera alors deux conteneurs différents, un pour l'interface utilisateur et l'autre pour l'API basés sur deux images distinctes : 
- `validataetalabstudio-validata` pour l'interface utilisateur (`preprodvalidataetalabstudio-validata` en preprod)
- `validataetalabstudio-validata_api` pour l'API (`preprodvalidataetalabstudio-validata_api` en preprod).
Il faudra également arrêter et supprimer les anciens conteneurs qui servaient en prod et preprod pour l'API `validata-api_prod` et `validata-api_preprod` ainsi que supprimer les images sur lesquelles étaient basées ces 2 conteneurs `apivalidataetalabstudio-validata` et `preprodapivalidataetalabstudio-validata`.

2023-11-03 15:07 UTC, amelie-rondot commented
Je me suis permise de rajouter un `README.md` dans le cadre de cette PR pour, en particulier, bien détailler la procédure de déploiement de l'interface utilisateur et de l'API de Validata Table utilisée actuellement.
Cette documentation est une base de travail qui peut être complétée / corrigée. En particulier il serait intéressant d'y intégrer les caractéristiques techniques du serveur de data.gouv, sur lequel sont hébergées l'interface utilisateur et l'API de Validata Table.

2023-11-05 20:51 UTC, geoffreyaldebert approved these changes
thanks ! it seems good for me :) let's try it in preprod ;)

2023-11-06 07:55 UTC, merged